# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1221, 664)
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame2 = QtWidgets.QFrame(self.centralwidget)
        self.frame2.setGeometry(QtCore.QRect(10, 0, 1261, 811))
        self.frame2.setStyleSheet("")
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        self.layoutWidget = QtWidgets.QWidget(self.frame2)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 50, 511, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_1 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        self.pushButton_1.setStyleSheet("QPushButton{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgb(34, 244, 255), stop:1\n"
" rgba(20,249,255,100));\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:5px;\n"
"border-color: rgb(0, 0, 0);}\n"
"QPushButton:hover { background-color: rgb(150,232,250,100); }\n"
"QPushButton:pressed {  background-color: rgb(0,232,250,100); }")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("bin/图标/new_model.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_1.setIcon(icon)
        self.pushButton_1.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_1.setCheckable(False)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("QPushButton{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgb(34, 244, 255), stop:1\n"
" rgba(20,249,255,100));\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:5px;\n"
"border-color: rgb(0, 0, 0);}\n"
"QPushButton:hover { background-color: rgb(150,232,250,100); }\n"
"QPushButton:pressed {  background-color: rgb(0,232,250,100); }")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("bin/图标/open_model.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setStyleSheet("QPushButton{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgb(34, 244, 255), stop:1\n"
" rgba(20,249,255,100));\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:5px;\n"
"border-color: rgb(0, 0, 0);}\n"
"QPushButton:hover { background-color: rgb(150,232,250,100); }\n"
"QPushButton:pressed {  background-color: rgb(0,232,250,100); }")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("bin/图标/train_model.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setStyleSheet("QPushButton{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgb(34, 244, 255), stop:1\n"
" rgba(20,249,255,100));\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:5px;\n"
"border-color: rgb(0, 0, 0);}\n"
"QPushButton:hover { background-color: rgb(150,232,250,100); }\n"
"QPushButton:pressed {  background-color: rgb(0,232,250,100); }")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("bin/图标/save_model.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.label_12 = QtWidgets.QLabel(self.frame2)
        self.label_12.setGeometry(QtCore.QRect(550, 20, 91, 20))
        self.label_12.setObjectName("label_12")
        self.listView_2 = QtWidgets.QListView(self.frame2)
        self.listView_2.setGeometry(QtCore.QRect(20, 130, 391, 341))
        self.listView_2.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0,y1:0, x2:0,y2:0,stop:0\n"
"rgba(255,255,255,100), stop:1\n"
"rgba(255,255,250,100) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);}\n"
"\n"
"")
        self.listView_2.setObjectName("listView_2")
        self.listView_3 = QtWidgets.QListView(self.frame2)
        self.listView_3.setGeometry(QtCore.QRect(430, 130, 371, 231))
        self.listView_3.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0,y1:0, x2:0,y2:0,stop:0\n"
"rgba(255,255,255,100), stop:1\n"
"rgba(255,255,250,100) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);}\n"
"\n"
"")
        self.listView_3.setObjectName("listView_3")
        self.listView_5 = QtWidgets.QListView(self.frame2)
        self.listView_5.setGeometry(QtCore.QRect(430, 370, 371, 261))
        self.listView_5.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0,y1:0, x2:0,y2:0,stop:0\n"
"rgba(255,255,255,100), stop:1\n"
"rgba(255,255,250,100) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);}\n"
"\n"
"")
        self.listView_5.setObjectName("listView_5")
        self.frame = QtWidgets.QFrame(self.frame2)
        self.frame.setGeometry(QtCore.QRect(410, 120, 411, 251))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(30, 20, 101, 21))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(30, 40, 351, 191))
        self.label_17.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgba(255,255,255,255), stop:1\n"
"rgba(255,255,255,255) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.frame_2 = QtWidgets.QFrame(self.frame2)
        self.frame_2.setGeometry(QtCore.QRect(20, 130, 381, 331))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 111, 21))
        self.label_11.setStyleSheet("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 40, 341, 281))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setStyleSheet("*{\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setStyleSheet("*{\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 1, 1, 1)
        self.label_0 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_0.sizePolicy().hasHeightForWidth())
        self.label_0.setSizePolicy(sizePolicy)
        self.label_0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_0.setObjectName("label_0")
        self.gridLayout.addWidget(self.label_0, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setStyleSheet("*{\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setStyleSheet("*{\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setStyleSheet("*{\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame2)
        self.frame_3.setGeometry(QtCore.QRect(810, 130, 371, 231))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setGeometry(QtCore.QRect(20, 10, 121, 21))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_47 = QtWidgets.QLabel(self.frame_3)
        self.label_47.setGeometry(QtCore.QRect(10, 30, 341, 191))
        self.label_47.setStyleSheet("*{\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_47.setText("")
        self.label_47.setObjectName("label_47")
        self.frame_4 = QtWidgets.QFrame(self.frame2)
        self.frame_4.setGeometry(QtCore.QRect(430, 380, 390, 240))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_24 = QtWidgets.QLabel(self.frame_4)
        self.label_24.setGeometry(QtCore.QRect(0, 0, 151, 20))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 351, 211))
        self.label_18.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgba(255,255,255,255), stop:1\n"
"rgba(255,255,255,255) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame2)
        self.pushButton_9.setGeometry(QtCore.QRect(700, 50, 121, 69))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setStyleSheet("QPushButton{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgb(34, 244, 255), stop:1\n"
" rgba(20,249,255,100));\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:5px;\n"
"border-color: rgb(0, 0, 0);}\n"
"QPushButton:hover { background-color: rgb(150,232,250,100); }\n"
"QPushButton:pressed {  background-color: rgb(0,232,250,100); }")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("bin/图标/download_model.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.listView_6 = QtWidgets.QListView(self.frame2)
        self.listView_6.setGeometry(QtCore.QRect(810, 370, 361, 261))
        self.listView_6.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0,y1:0, x2:0,y2:0,stop:0\n"
"rgba(255,255,255,100), stop:1\n"
"rgba(255,255,250,100) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);}\n"
"\n"
"")
        self.listView_6.setObjectName("listView_6")
        self.listView_4 = QtWidgets.QListView(self.frame2)
        self.listView_4.setGeometry(QtCore.QRect(810, 130, 361, 231))
        self.listView_4.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0,y1:0, x2:0,y2:0,stop:0\n"
"rgba(255,255,255,100), stop:1\n"
"rgba(255,255,250,100) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);}\n"
"\n"
"")
        self.listView_4.setObjectName("listView_4")
        self.frame_9 = QtWidgets.QFrame(self.frame2)
        self.frame_9.setGeometry(QtCore.QRect(810, 380, 371, 231))
        self.frame_9.setStyleSheet("")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_45 = QtWidgets.QLabel(self.frame_9)
        self.label_45.setGeometry(QtCore.QRect(20, 0, 121, 21))
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.frame_9)
        self.label_46.setGeometry(QtCore.QRect(10, 20, 341, 211))
        self.label_46.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgba(255,255,255,255), stop:1\n"
"rgba(255,255,255,255) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.label_48 = QtWidgets.QLabel(self.frame2)
        self.label_48.setGeometry(QtCore.QRect(30, 510, 91, 20))
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.listView_12 = QtWidgets.QListView(self.frame2)
        self.listView_12.setGeometry(QtCore.QRect(20, 500, 391, 121))
        self.listView_12.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0,y1:0, x2:0,y2:0,stop:0\n"
"rgba(255,255,255,100), stop:1\n"
"rgba(255,255,250,100) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);}\n"
"\n"
"")
        self.listView_12.setObjectName("listView_12")
        self.progressBar = QtWidgets.QProgressBar(self.frame2)
        self.progressBar.setGeometry(QtCore.QRect(40, 540, 371, 61))
        self.progressBar.setProperty("value", 26)
        self.progressBar.setObjectName("progressBar")
        self.listView_12.raise_()
        self.listView_4.raise_()
        self.layoutWidget.raise_()
        self.label_12.raise_()
        self.listView_2.raise_()
        self.listView_3.raise_()
        self.listView_5.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.pushButton_9.raise_()
        self.listView_6.raise_()
        self.frame_9.raise_()
        self.label_48.raise_()
        self.progressBar.raise_()
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, 0, 1221, 641))
        self.listView.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgba(214,249,255,100), stop:1\n"
"rgba(158,232,250,100) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);}\n"
"\n"
"")
        self.listView.setObjectName("listView")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1370, 830, 114, 69))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1300, 470, 115, 69))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setGeometry(QtCore.QRect(0, -20, 1411, 751))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label = QtWidgets.QLabel(self.frame_10)
        self.label.setGeometry(QtCore.QRect(0, 0, 1221, 661))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("bin/固定资源/start.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame_10)
        self.label_3.setGeometry(QtCore.QRect(400, 40, 581, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_10)
        self.pushButton.setGeometry(QtCore.QRect(130, 530, 141, 61))
        self.pushButton.setStyleSheet("QPushButton{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgba(20,249,255,100), stop:1\n"
"rgba(20,232,250,100) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:5px;\n"
"border-color: rgb(0, 0, 0);}\n"
"QPushButton:hover { background-color: rgb(150,232,250,100); }\n"
"QPushButton:pressed {  background-color: rgb(0,232,250,100); }")
        self.pushButton.setObjectName("pushButton")
        self.frame1 = QtWidgets.QFrame(self.centralwidget)
        self.frame1.setGeometry(QtCore.QRect(0, -20, 1331, 671))
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame1)
        self.layoutWidget2.setGeometry(QtCore.QRect(250, 60, 356, 71))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setStyleSheet("QPushButton{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgb(34, 244, 255), stop:1\n"
" rgba(20,249,255,100));\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:5px;\n"
"border-color: rgb(0, 0, 0);}\n"
"QPushButton:hover { background-color: rgb(150,232,250,100); }\n"
"QPushButton:pressed {  background-color: rgb(0,232,250,100); }")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("bin/图标/choose_model.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon5)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("QPushButton{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgb(34, 244, 255), stop:1\n"
" rgba(20,249,255,100));\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:5px;\n"
"border-color: rgb(0, 0, 0);}\n"
"QPushButton:hover { background-color: rgb(150,232,250,100); }\n"
"QPushButton:pressed {  background-color: rgb(0,232,250,100); }")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("bin/图标/bug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon6)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.label_13 = QtWidgets.QLabel(self.frame1)
        self.label_13.setGeometry(QtCore.QRect(550, 40, 81, 16))
        self.label_13.setObjectName("label_13")
        self.listView_7 = QtWidgets.QListView(self.frame1)
        self.listView_7.setGeometry(QtCore.QRect(10, 150, 391, 241))
        self.listView_7.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0,y1:0, x2:0,y2:0,stop:0\n"
"rgba(255,255,255,100), stop:1\n"
"rgba(255,255,250,100) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);}\n"
"\n"
"")
        self.listView_7.setObjectName("listView_7")
        self.listView_8 = QtWidgets.QListView(self.frame1)
        self.listView_8.setGeometry(QtCore.QRect(420, 150, 391, 241))
        self.listView_8.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0,y1:0, x2:0,y2:0,stop:0\n"
"rgba(255,255,255,100), stop:1\n"
"rgba(255,255,250,100) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);}\n"
"\n"
"")
        self.listView_8.setObjectName("listView_8")
        self.listView_9 = QtWidgets.QListView(self.frame1)
        self.listView_9.setGeometry(QtCore.QRect(10, 410, 391, 241))
        self.listView_9.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0,y1:0, x2:0,y2:0,stop:0\n"
"rgba(255,255,255,100), stop:1\n"
"rgba(255,255,250,100) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);}\n"
"\n"
"")
        self.listView_9.setObjectName("listView_9")
        self.listView_10 = QtWidgets.QListView(self.frame1)
        self.listView_10.setGeometry(QtCore.QRect(820, 410, 391, 241))
        self.listView_10.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0,y1:0, x2:0,y2:0,stop:0\n"
"rgba(255,255,255,100), stop:1\n"
"rgba(255,255,250,100) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);}\n"
"\n"
"")
        self.listView_10.setObjectName("listView_10")
        self.frame_5 = QtWidgets.QFrame(self.frame1)
        self.frame_5.setGeometry(QtCore.QRect(0, 150, 390, 240))
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 50, 361, 181))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 3, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setStyleSheet("*{\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 1, 3, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_5.addWidget(self.label_38, 1, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_27.setStyleSheet("*{\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 1, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_5.addWidget(self.label_40, 2, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_31.setStyleSheet("*{\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 3, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_33.setStyleSheet("*{\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 2, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setStyleSheet("*{\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 0, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_29.setStyleSheet("*{\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 2, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setStyleSheet("*{\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 0, 3, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 3, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_44.setStyleSheet("*{\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_44.setText("")
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 3, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame_5)
        self.label_34.setGeometry(QtCore.QRect(30, 20, 151, 16))
        self.label_34.setStyleSheet("")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.frame_7 = QtWidgets.QFrame(self.frame1)
        self.frame_7.setGeometry(QtCore.QRect(10, 400, 390, 251))
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_36 = QtWidgets.QLabel(self.frame_7)
        self.label_36.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_41 = QtWidgets.QLabel(self.frame_7)
        self.label_41.setGeometry(QtCore.QRect(20, 40, 351, 201))
        self.label_41.setStyleSheet("*{\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.frame_6 = QtWidgets.QFrame(self.frame1)
        self.frame_6.setGeometry(QtCore.QRect(410, 150, 401, 240))
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_35 = QtWidgets.QLabel(self.frame_6)
        self.label_35.setGeometry(QtCore.QRect(20, 10, 91, 16))
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        self.label_19.setGeometry(QtCore.QRect(20, 30, 371, 201))
        self.label_19.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgba(255,255,255,255), stop:1\n"
"rgba(255,255,255,255) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.frame_8 = QtWidgets.QFrame(self.frame1)
        self.frame_8.setGeometry(QtCore.QRect(810, 410, 401, 241))
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_37 = QtWidgets.QLabel(self.frame_8)
        self.label_37.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_20 = QtWidgets.QLabel(self.frame_8)
        self.label_20.setGeometry(QtCore.QRect(20, 30, 371, 201))
        self.label_20.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgba(255,255,255,255), stop:1\n"
"rgba(255,255,255,255) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame1)
        self.pushButton_10.setGeometry(QtCore.QRect(660, 60, 173, 69))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setStyleSheet("QPushButton{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgb(34, 244, 255), stop:1\n"
" rgba(20,249,255,100));\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:5px;\n"
"border-color: rgb(0, 0, 0);}\n"
"QPushButton:hover { background-color: rgb(150,232,250,100); }\n"
"QPushButton:pressed {  background-color: rgb(0,232,250,100); }")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("bin/图标/question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon7)
        self.pushButton_10.setObjectName("pushButton_10")
        self.frame_12 = QtWidgets.QFrame(self.frame1)
        self.frame_12.setGeometry(QtCore.QRect(410, 410, 401, 240))
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_51 = QtWidgets.QLabel(self.frame_12)
        self.label_51.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.frame_12)
        self.label_52.setGeometry(QtCore.QRect(20, 30, 371, 201))
        self.label_52.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgba(255,255,255,255), stop:1\n"
"rgba(255,255,255,255) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_52.setText("")
        self.label_52.setObjectName("label_52")
        self.frame_11 = QtWidgets.QFrame(self.frame1)
        self.frame_11.setGeometry(QtCore.QRect(810, 150, 401, 240))
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_49 = QtWidgets.QLabel(self.frame_11)
        self.label_49.setGeometry(QtCore.QRect(20, 10, 91, 16))
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.frame_11)
        self.label_50.setGeometry(QtCore.QRect(20, 30, 371, 201))
        self.label_50.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0.5,y1:0, x2:0.5,y2:1,stop:0\n"
"rgba(255,255,255,255), stop:1\n"
"rgba(255,255,255,255) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:4px;\n"
"border-color: rgb(0, 0, 0);}")
        self.label_50.setText("")
        self.label_50.setObjectName("label_50")
        self.listView_11 = QtWidgets.QListView(self.frame1)
        self.listView_11.setGeometry(QtCore.QRect(820, 150, 391, 241))
        self.listView_11.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0,y1:0, x2:0,y2:0,stop:0\n"
"rgba(255,255,255,100), stop:1\n"
"rgba(255,255,250,100) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);}\n"
"\n"
"")
        self.listView_11.setObjectName("listView_11")
        self.listView_13 = QtWidgets.QListView(self.frame1)
        self.listView_13.setGeometry(QtCore.QRect(420, 410, 391, 241))
        self.listView_13.setStyleSheet("*{background-color: qlineargradient(spread:pad,x1:0,y1:0, x2:0,y2:0,stop:0\n"
"rgba(255,255,255,100), stop:1\n"
"rgba(255,255,250,100) );\n"
"border:1px solid rgba(205.92,92,255);\n"
"border-radius:10px;\n"
"border-color: rgb(0, 0, 0);}\n"
"\n"
"")
        self.listView_13.setObjectName("listView_13")
        self.listView_13.raise_()
        self.listView_11.raise_()
        self.layoutWidget.raise_()
        self.label_13.raise_()
        self.listView_7.raise_()
        self.listView_8.raise_()
        self.listView_9.raise_()
        self.listView_10.raise_()
        self.frame_5.raise_()
        self.frame_7.raise_()
        self.frame_6.raise_()
        self.frame_8.raise_()
        self.pushButton_10.raise_()
        self.frame_12.raise_()
        self.frame_11.raise_()
        self.listView.raise_()
        self.frame2.raise_()
        self.pushButton_6.raise_()
        self.pushButton_4.raise_()
        self.frame1.raise_()
        self.frame_10.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actiondalao = QtWidgets.QAction(MainWindow)
        self.actiondalao.setObjectName("actiondalao")
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.toolBar.addAction(self.actiondalao)
        self.toolBar.addAction(self.actionopen)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "智能诊断系统"))
        self.pushButton_1.setText(_translate("MainWindow", "新建网络"))
        self.pushButton_2.setText(_translate("MainWindow", "打开网络"))
        self.pushButton_3.setText(_translate("MainWindow", "训练网络"))
        self.pushButton_5.setText(_translate("MainWindow", "保存网络"))
        self.label_12.setText(_translate("MainWindow", "模型训练"))
        self.label_22.setText(_translate("MainWindow", "网络结构"))
        self.label_11.setText(_translate("MainWindow", "训练网络信息"))
        self.label_0.setText(_translate("MainWindow", "网络类型"))
        self.label_14.setText(_translate("MainWindow", "网络名称"))
        self.label_2.setText(_translate("MainWindow", "网络输出"))
        self.label_4.setText(_translate("MainWindow", "网络输入"))
        self.label_5.setText(_translate("MainWindow", "诊断部件"))
        self.label_23.setText(_translate("MainWindow", "训练数据情况"))
        self.label_24.setText(_translate("MainWindow", "准确率变化趋势图"))
        self.pushButton_9.setText(_translate("MainWindow", "下载数据插件"))
        self.label_45.setText(_translate("MainWindow", "误差变化趋势图"))
        self.label_48.setText(_translate("MainWindow", "训练进度"))
        self.pushButton_6.setText(_translate("MainWindow", "实时诊断"))
        self.pushButton_4.setText(_translate("MainWindow", "停止训练"))
        self.label_3.setText(_translate("MainWindow", "深度学习故障诊断系统"))
        self.pushButton.setText(_translate("MainWindow", "进入"))
        self.pushButton_8.setText(_translate("MainWindow", "模型选择"))
        self.pushButton_7.setText(_translate("MainWindow", "离线诊断"))
        self.label_13.setText(_translate("MainWindow", "故障诊断"))
        self.label_21.setText(_translate("MainWindow", "网络名称"))
        self.label_30.setText(_translate("MainWindow", "训练步数"))
        self.label_28.setText(_translate("MainWindow", "诊断部件"))
        self.label_38.setText(_translate("MainWindow", "网络输出"))
        self.label_26.setText(_translate("MainWindow", "网络输入"))
        self.label_40.setText(_translate("MainWindow", "学习率\n"
"优化器"))
        self.label_32.setText(_translate("MainWindow", "网络类型"))
        self.label_43.setText(_translate("MainWindow", "批样本数"))
        self.label_34.setText(_translate("MainWindow", "数据及诊断网络信息"))
        self.label_36.setText(_translate("MainWindow", "诊断结果"))
        self.label_35.setText(_translate("MainWindow", "振动原始波形"))
        self.label_37.setText(_translate("MainWindow", "频谱趋势图"))
        self.pushButton_10.setText(_translate("MainWindow", "专家知识"))
        self.label_51.setText(_translate("MainWindow", "诊断解释"))
        self.label_49.setText(_translate("MainWindow", "频谱阶次图"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actiondalao.setText(_translate("MainWindow", "故障诊断"))
        self.actionopen.setText(_translate("MainWindow", "模型训练"))
